#!/usr/bin/env node
// Generates .prettierrc.cjs and .prettierignore from FORMATTER_CONFIG.md.
// CommonJS on purpose (.cjs): if your package.json has "type": "module",
// a plain .js file here would be parsed as ESM and crash on `require`/module.exports.
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(__dirname, 'FORMATTER_CONFIG.md');

function parseConfig(text) {
  const match = text.match(/```config\n([\s\S]*?)```/);
  if (!match) {
    console.error('Could not find a ```config fenced block in FORMATTER_CONFIG.md');
    process.exit(1);
  }
  const values = {};
  for (const line of match[1].split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return values;
}

const bool = (v, fallback) => (v === undefined || v === '' ? fallback : v === 'true');
const num = (v, fallback) => (v === undefined || v === '' ? fallback : Number(v));
const str = (v, fallback) => (v === undefined || v === '' ? fallback : v);

function buildPrettierRc(cfg) {
  const singleQuote = bool(cfg.USE_SINGLE_QUOTES, true);
  const semi = bool(cfg.USE_SEMICOLONS, true);
  const printWidth = num(cfg.PRINT_WIDTH, 100);
  const tabWidth = num(cfg.INDENT_SIZE, 2);
  const useTabs = str(cfg.INDENT_STYLE, 'space') === 'tab';
  const trailingComma = str(cfg.TRAILING_COMMA, 'all');
  const bracketSpacing = bool(cfg.BRACKET_SPACING, true);
  const arrowParens = str(cfg.ARROW_PARENS, 'always');
  const endOfLine = str(cfg.END_OF_LINE, 'lf');
  const proseWrap = str(cfg.PROSE_WRAP, 'preserve');
  const jsonTrailingComma = str(cfg.JSON_TRAILING_COMMA, 'none');
  const markdownProseWrap = str(cfg.MARKDOWN_PROSE_WRAP, 'always');
  const yamlIndent = num(cfg.YAML_INDENT_SIZE, 2);

  return `// Generated by .formatter/sync.cjs from .formatter/FORMATTER_CONFIG.md — do not hand-edit.
module.exports = {
  printWidth: ${printWidth},
  tabWidth: ${tabWidth},
  useTabs: ${useTabs},
  singleQuote: ${singleQuote},
  semi: ${semi},
  trailingComma: '${trailingComma}',
  bracketSpacing: ${bracketSpacing},
  arrowParens: '${arrowParens}',
  endOfLine: '${endOfLine}',
  proseWrap: '${proseWrap}',
  overrides: [
    { files: '*.json', options: { trailingComma: '${jsonTrailingComma}' } },
    { files: '*.md', options: { proseWrap: '${markdownProseWrap}' } },
    { files: ['*.yml', '*.yaml'], options: { tabWidth: ${yamlIndent} } },
  ],
};
`;
}

// Blacklist, not a whitelist: a whitelist-style ignore file (/* + !/src/)
// only unignores a root-level src/, so it silently breaks in a monorepo with
// apps/*/src or packages/*/src. Blacklisting known-noise formats everything
// else by default, regardless of how many source roots the repo has.
const BASE_IGNORE = [
  'node_modules/',
  'vendor/',
  'build/',
  'dist/',
  'coverage/',
  '.cache/',
  '.next/',
  '*.min.js',
  '*.min.css',
  '*.log',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  '.DS_Store',
  'Thumbs.db',
  '*.tmp',
  '*.temp',
];

function buildPrettierIgnore(cfg) {
  const extra = (cfg.EXTRA_IGNORE_PATTERNS || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const lines = [
    '# Generated by .formatter/sync.cjs from .formatter/FORMATTER_CONFIG.md — do not hand-edit.',
    '# Blacklist, not a whitelist — safe for monorepos with multiple source roots.',
    ...BASE_IGNORE,
  ];
  if (extra.length) lines.push('', '# From EXTRA_IGNORE_PATTERNS', ...extra);
  return lines.join('\n') + '\n';
}

function main() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error(`Missing ${CONFIG_PATH}`);
    process.exit(1);
  }
  const cfg = parseConfig(fs.readFileSync(CONFIG_PATH, 'utf8'));

  fs.writeFileSync(path.join(ROOT, '.prettierrc.cjs'), buildPrettierRc(cfg));
  fs.writeFileSync(path.join(ROOT, '.prettierignore'), buildPrettierIgnore(cfg));

  console.log('\x1b[32m✔ Generated .prettierrc.cjs and .prettierignore\x1b[0m');
  console.log('\nNext steps:');
  console.log('  npm install -D prettier   # if not already installed');
  console.log('  npx prettier --write .');
}

main();
